# Generated by Django 2.2.4 on 2019-08-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drom_pars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingdb',
            name='price',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='parsingdb',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
