# Generated by Django 2.2.4 on 2019-08-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drom_pars', '0002_auto_20190807_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingdb',
            name='href',
            field=models.SlugField(max_length=255),
        ),
    ]
